### ISSUE TITLE
bug: release 0.7.0 returns "unstable" instead of 0.7.0

### ISSUE THREAD

**Issue by AndriyKalashnykov** [nukleros/operator-builder#55]
release 0.7.0 returns "unstable" instead of 0.7.0

Steps to reproduce:

$ sudo rm /usr/local/bin/operator-builder
$ which operator-builder 
$ VERSION=v0.7.0
$ OS=Linux
$ ARCH=x86_64
$ wget https://github.com/nukleros/operator-builder/releases/download/${VERSION}/operator-builder_${VERSION}_${OS}_${ARCH}.tar.gz -O - | tar -xz && sudo mv operator-builder /usr/local/bin/operator-builder

$ operator-builder version
unstable

**Comment by scottd018** [comment]
This has since been fixed and reports correctly:

```
operator-builder version
0.8.0
```
